---
abstract: 'a simple setup for a new module'
author:
  - 'Johan Vromans <jv@cpan.org>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Module-Setup
no_index:
  directory:
    - t
    - inc
  file:
    - lib/App/Module/Setup/Templates/Default.pm
version: 0.05
